### ISSUE TITLE
コマを置く場所がなくて順番を飛ばした後に例外発生

### ISSUE THREAD

**Issue by arimakaoru** [Oiwane/othello#2]
# 問題の内容
黒(プレイヤー)のコマを置く場所がなくて順番が飛ばされた後に、白(CPU)の番で例外が発生した。

# 実行環境
JDK 10.0.2
macOS High Sierra 10.13.6 

# 発生した例外のスクリーンショット
<img width="726" alt="2018-12-23 20 03 16" src="https://user-images.githubusercontent.com/46063788/50382967-e295e180-06ed-11e9-9daf-9f8169deea41.png">

**Comment by Oiwane** [comment]
修正しました  
修正内容については`README.md`をご覧ください
